name: agendamento_vacina
description: Sistema de agendamento para vacinação.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  brasil_fields: ^0.6.1
  cpf_cnpj_validator: ^1.0.5
  http: ^0.12.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - json/
  uses-material-design: true
